[build]
  # Directory to change to before starting build. Default is root of repo.
  base = "/"
  
  # Directory that contains the deployed site. Default is "build" for React apps.
  publish = "themis-client-final/build"
  
  # Updated build command to ensure dependencies are installed correctly
  command = "chmod +x netlify-prebuild.sh && ./netlify-prebuild.sh && cd themis-client-final && npm install && npm run build"

# Plugin to install function dependencies
[[plugins]]
  package = "@netlify/plugin-functions-install-core"

# Redirects for SPA routing - more specific first
[[redirects]]
  from = "/static/*"
  to = "/static/:splat"
  status = 200

[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Catch-all redirect for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 