[build]
  base = "project-collector"
  command = "npm run build"
  publish = "project-collector/build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://api.pmo.projects.mod.qa/api"
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_BASE_URL = "https://collector.pmo.projects.mod.qa"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://api.pmo.projects.mod.qa/api"
  REACT_APP_ENVIRONMENT = "staging"
  REACT_APP_BASE_URL = "https://collector-staging.netlify.app"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://api.pmo.projects.mod.qa/api"
  REACT_APP_ENVIRONMENT = "staging"
  REACT_APP_BASE_URL = "https://collector-staging.netlify.app" 