[build]
  command = "npm run build"
  publish = "build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_VERSION = "10.2.4"
  NPM_FLAGS = "--legacy-peer-deps"
  REACT_APP_SUPABASE_URL = "https://jxtsbjkfashodslayoaw.supabase.co"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co wss://*.supabase.co; img-src 'self' data: blob:; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; font-src 'self' data:;"

[context.production.environment]
  REACT_APP_API_URL = "https://api.pmo.projects.mod.qa/api"
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_BASE_URL = "https://pmo.projects.mod.qa"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://api.pmo.projects.mod.qa/api"
  REACT_APP_ENVIRONMENT = "staging"
  REACT_APP_BASE_URL = "https://themis-staging.netlify.app"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://api.pmo.projects.mod.qa/api"
  REACT_APP_ENVIRONMENT = "staging"
  REACT_APP_BASE_URL = "https://themis-staging.netlify.app" 