[build]
  base = "themis-client-final"
  command = "npm run build"
  publish = "themis-client-final/build"
  functions = "themis-client-final/netlify/functions"

[build.environment]
  NODE_VERSION = "18.17.1"
  NPM_VERSION = "10.2.4"
  NPM_FLAGS = "--legacy-peer-deps"
  REACT_APP_SUPABASE_URL = "https://jxtsbjkfashodslayoaw.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4dHNiamtmYXNob2RzbGF5b2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTU4ODY3MDEsImV4cCI6MjAzMTQ2MjcwMX0.UdqJKIL4QFaQqEi4A07s3m_9BZ5LWcXQK1IUjEJtv34"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.supabase.co wss://*.supabase.co https://identitytoolkit.googleapis.com https://securetoken.googleapis.com; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https://lh3.googleusercontent.com;"

[context.production.environment]
  REACT_APP_API_URL = "https://api.pmo.projects.mod.qa/api"
  REACT_APP_ENVIRONMENT = "production"
  REACT_APP_BASE_URL = "https://pmo.projects.mod.qa"
  REACT_APP_SUPABASE_URL = "https://jxtsbjkfashodslayoaw.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4dHNiamtmYXNob2RzbGF5b2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTU4ODY3MDEsImV4cCI6MjAzMTQ2MjcwMX0.UdqJKIL4QFaQqEi4A07s3m_9BZ5LWcXQK1IUjEJtv34"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://api.pmo.projects.mod.qa/api"
  REACT_APP_ENVIRONMENT = "staging"
  REACT_APP_BASE_URL = "https://themis-staging.netlify.app"
  REACT_APP_SUPABASE_URL = "https://jxtsbjkfashodslayoaw.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4dHNiamtmYXNob2RzbGF5b2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTU4ODY3MDEsImV4cCI6MjAzMTQ2MjcwMX0.UdqJKIL4QFaQqEi4A07s3m_9BZ5LWcXQK1IUjEJtv34"

[context.branch-deploy.environment]
  REACT_APP_API_URL = "https://api.pmo.projects.mod.qa/api"
  REACT_APP_ENVIRONMENT = "staging"
  REACT_APP_BASE_URL = "https://themis-staging.netlify.app"
  REACT_APP_SUPABASE_URL = "https://jxtsbjkfashodslayoaw.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp4dHNiamtmYXNob2RzbGF5b2F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MTU4ODY3MDEsImV4cCI6MjAzMTQ2MjcwMX0.UdqJKIL4QFaQqEi4A07s3m_9BZ5LWcXQK1IUjEJtv34"

# Settings in the [dev] context are for local netlify dev
[dev]
  command = "npm start"
  port = 8888
  publish = "build" 